// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Todo struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
	User   *User  `json:"user"`
	Body   string `json:"body"`
}

func (Todo) IsEntity() {}

type User struct {
	ID    string  `json:"id"`
	Todos []*Todo `json:"todos"`
}

func (User) IsEntity() {}
